### ISSUE TITLE
Homonuclear parametrization

### ISSUE THREAD

**Issue by sally008** [pekkosk/hotbit#17]
Hello,

I am trying to learn how to parametrize DFTB with hotbit. I am able to construct the CH and HC Slater Koster tables but I am having trouble doing the homonuclear cases (e.g., HH and CC). I noticed in the AuAu example that  dimer, "bulk", and homogeneous clusters are used. I constructed a dimer and bulk trajectory for hydrogen by just copying the gold examples (and adjusting the bond lengths in the dimer). However, I am wondering if this is sufficient for the homogeneous cluster (i.e., replacing Au with H in the Au12-.xyz file and decreasing the bond lengths between the atoms). Any help is appreciated.

-Sarah

**Comment by pekkosk** [comment]
Using the geometry of the homogeneous cluster Au12- for other elements is a bad idea, as the geometry is specific for gold. For H dimer may be enough (since H clusters don't quite occur in nature) and for CC one could use graphene, diamond, nanotubes, fullerenes, and a selection of symmetric hydrocarbons.

**Comment by sally008** [comment]
Makes sense. Thank you!
